# Generated by Django 6.0.4 on 2026-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=100, verbose_name='Код для клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_promotion_code_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID промокода Stripe'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='stripe_tax_rate_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID налога Stripe'),
        ),
    ]
