# Generated by Django 6.0.4 on 2026-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_discount_code_discount_stripe_promotion_code_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.tax'),
        ),
    ]
