# Generated by Django 6.0.4 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_order_tax_item_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.tax'),
        ),
    ]
