# Generated by Django 6.0.4 on 2026-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='stripe_coupon_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='stripe_promotion_code_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='stripe_tax_rate_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id_eur',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID EUR купона Stripe'),
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id_usd',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID USD купона Stripe'),
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_promotion_code_id_eur',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID EUR промокода Stripe'),
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_promotion_code_id_usd',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID USD промокода Stripe'),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_rate_id_eur',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID EUR налога Stripe'),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_rate_id_usd',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID USD налога Stripe'),
        ),
    ]
