# Generated by Django 6.0.4 on 2026-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_orderitem_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код для клиента'),
        ),
    ]
